# CircleCI configuration file
version: 2.1

jobs:
  testJob:
    docker:
    - image: cimg/base:2023.03
    steps:
      - run: 
          no_output_timeout: 30m
          command:  echo "Hello, from CircleCI!"
          


workflows:
  workflowtest:
    jobs:
     - testJob
