# CircleCI configuration file
version: 2.1

jobs:
  testJob:
    docker:
    - image: cimg/base:2023.03
    steps:
      - run: 
          command:  sudo ulimit -u unlimited`




          


workflows:
  workflowtest:
    jobs:
     - testJob


ryan-lumin