version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/base:2023:03 # the primary container, where your job's commands are run
    steps:
      - run: echo "hello world" # run the `echo` command

workflows:
  my-workflow:
    jobs:
      - hello-job