version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor:
        name: win/default
        shell: powershell.exe
        version: 2023.04.1
    steps:
      - checkout
      - run: systeminfo
      - run: docker info
      - run: docker run -it mcr.microsoft.com/windows/nanoserver:ltsc2022 cmd.exe