version: 2.1

orbs:
  win: circleci/windows@5.0

workflows:
  test-login:
    jobs:
      - creds
jobs:
  creds:
    executor: win/server-2022
    steps:
      - run: 
          command: |
            echo $Rain
            whoami
          shell: powershell.exe