# CircleCI configuration file
version: 2.1

parameters:
  resource-class-size:
    type: string
    default: "medium"


jobs:
  testJob:
    docker:
    - image: ghcr.io/cirruslabs/flutter:3.10.5
    steps:
      - checkout
      # Whatever you want to do
      - run: echo "Hello, from CircleCI!"



workflows:
  workflowtest:
    jobs:
     - testJob
