version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor:
        name: windows/default
        shell: powershell.exe
        version: "2023.04.1"
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Check docker"
          shell: powershell.exe
          command: |
            docker info
            docker run -it mcr.microsoft.com/windows/nanoserver:ltsc2022 cmd.exe