version: 2.1
orbs:
  python: circleci/python@2.1.1

workflows:
  sanity_memix_web_workflow:
    jobs:
      - sanity_memix_web_job

jobs:
  sanity_memix_web_job:
    docker:
      - image: cimg/python:3.10.5

    steps:
      - checkout
      - run: 
          name: Install Paver
          command: |
            pip install -U Paver
      - run:   
         name: Run Paver Command       
         command: |      
          paver run_all web prod
    

