# CircleCI configuration file
version: 2.1

parameters:
  resource-class-size:
    type: string
    default: "medium"


jobs:
  testJob:
    docker:
    - image: circleci/php:8.0-apache-node-browsers
    steps:
      - checkout
      # Whatever you want to do
      - run: echo "Hello, from CircleCI!"
      - run: image ls



workflows:
  workflowtest:
    jobs:
     - testJob
