# CircleCI configuration file
version: 2.1

jobs:
  testJob:
    docker:
    - image: cimg/base:2023.03
    steps:
      - run:
          name:  Print pipeline number?
          command: |
              echo "pipeline.number:  $pipeline.number"




workflows:
  workflowtest:
    jobs:
     - testJob

### Update for today
