version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor:
        name: win/default
        shell: powershell.exe
        version: 2023.04.1
    steps:
      - checkout
      - run:
          name: create user
          shell: powershell.exe
          command: |
            New-Localuser -Name "TestUser" -NoPassword
            Get-LocalUser

workflows:
  my-workflow:
    jobs:
      - build