# CircleCI configuration file
version: 2.1

jobs:
  testJob:
    docker:
    - image: cimg/android:2023.02
    steps:
      - run: java -version


workflows:
  workflowtest:
    jobs:
     - testJob

### Comment to update build