version: 2.1

orbs:
  win: circleci/windows@5.0

workflows:
  test-login:
    jobs:
      - creds
jobs:
  creds:
    executor: win/server-2022
    steps:
      - run: 
          command: |
            $credential = New-Object System.Management.Automation.PSCredential ($Env:username, $Env:password)
            whoami
          shell: powershell.exe