# CircleCI configuration file
version: 2.1

jobs:
  newYobPython:
    docker:
    -  image: circleci/python:3.10.5
    steps:
    - run: 
        command: |
          python --version
  newBaseYob:
    docker:
      -  image: cimg/base:2022.05
    steps:
    - run: echo "Hello, it's me"
    
workflows:
  newWerkWerkWerk:
    jobs:
      - newYobPython
      - newBaseYob
