# CircleCI configuration file
version: 2.1

jobs:
  newYobPython:
    docker:
    -  image: cimg/python:3.10.5
    steps:
    - run: 
        command: |
          python -c 'print("Hello, from CircleCI")'

workflows:
  one-minute:
    triggers:
      - schedule:
         cron: "1,2,3,4 * * * * "
         filter:
          branches:
            only:
              - main
    jobs:
      - newYobPython

