version: 2.1

orbs:
  win: circleci/windows@5.0.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - run: |
          echo 'MY_VAR_1="one"' >> /tmp/my_env.bat
          echo 'MY_VAR_2="two"' >> /tmp/my_env.bat
      - run: |
          call /tmp/my_env.bat
          # run command here 
      - run: |
          call /tmp/my_env.bat
          # run other commands here


workflow:
  workflowuno:
    jobs:
      - build