version: 2.1
 
orbs:
  win: circleci/windows@5.0

workflows:
  test-login:
    jobs:
      - creds
jobs:
  creds:
    executor: win/server-2022
    steps:
      - run: 
          command: |
            $username
            $password  
            $credential = New-Object System.Management.Automation.PSCredential ($username, $securePassword)
            
            Invoke-Command -ComputerName localhost -Credential $credential 
            echo whoami

          shell: powershell.exe