version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor:
        name: win/default
        shell: powershell.exe
        version: 2023.04.1
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Check docker"
          shell: powershell.exe
          command: |
            docker info
            -Xallow-non-tty docker run -i mcr.microsoft.com/windows/nanoserver:ltsc2022 cmd.exe