# CircleCI configuration file
version: 2.1

parameters:
  resource-class-size:
    type: string
    default: "medium"


jobs:
  testJob:
    docker:
    - image: circleci/php:8.0-apache-node-browsers
    steps:
      - checkout
      # Whatever you want to do
      - run: sudo apt update
      - run: sudo apt install lsb-release ca-certificates apt-transport-https software-properties-common -y
      - run: sudo add-apt-repository ppa:ondrej/php
      - run: sudo apt install php8.1.1
      - run: sudo apt install php8.1common php8.1cli

workflows:
  workflowtest:
    jobs:
     - testJob
