version: 2.1

workflows:
  workflow-uno:
    jobs:
      - yjit-in-here

jobs:
  yjit-in-here:
    docker:
      - image: srockstyle/ruby-3.1-enable-yjit

    steps:
      - checkout
      - run:
          name: Yjit Installed?
          command: |
            ruby -v --yjit