# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: 
          name: Echo Env Var
          command: echo $Rain
          environment:
            Rain: Acid
            

workflows:
  hello:
    jobs:
      - build