# CircleCI configuration file
version: 2.1

jobs:
  newYob:
    docker:
    -  image: cimg/python:3.10.5
    -  image: cimg/base:2022.05
    steps:
    - run: echo "Hello, it's me"
    - run: 
        command: |
          python --version
    
workflows:
  newWerkWerkWerk:
    jobs:
      - newYob