# CircleCI configuration file
version: 2.1

jobs:
  newYobPython:
    docker:
    -  image: cimg/python:3.10.5
    steps:
    - run: 
        command: |
          python -c 'print("Hi")'

workflows:
  version: 2
  oneMinute:
    triggers:
      - schedule:
          cron: "1,2,3,4 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - newYobPython