# CircleCI configuration file
version: 2.1

jobs:
  jfrog-test-test-test:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - artifactory/install
      - artifactory/configure
      - artifactory/build-integration
orbs:
  artifactory: circleci/artifactory@1.0.0

workflows:
  hello:
    jobs:
      - jfrog-test-test-test