# CircleCI configuration file
version: 2.1

parameters:
  resource-class-size:
    type: string
    default: "medium"


jobs:
  testJob:
    docker:
    - image: cimg/base:2023.03
    resource_class: << pipeline.parameters.resource-class-size >>
    steps:
      - run: 
          command: timeout 10s tail -f /dev/null


# see if this works?

workflows:
  workflowtest:
    jobs:
     - testJob
