# CircleCI configuration file
version: 2.1

jobs:
  newYobHello:
    docker:
    - image: cimg/base:2023.03
    steps:
      - run: echo "Hello, from CircleCI!"
  newYobPython:
    docker:
    -  image: cimg/python:3.10.5
    steps:
    - run: 
        command: |
          python -c 'print("Hello, from Python!")'

workflows:
  version: 2
  noSchedule:
    jobs:
     - newYobHello
  oneMinute:
    triggers:
      - schedule:
          cron: "1,2,3,4 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - newYobPython