version: 2.1

workflows:
  test-login:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: livmade/windows
    steps:
      - run: 
          command: $credential = Get-Credential # You will be prompted for the username and password here.
          shell: powershell.exe