version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    docker:
      - image: cimg/android:2023.07.1
    steps:
      - checkout
      - run: ./gradlew androidDependencies
      - run: ./gradlew lint test
      - run: echo "Hello"

workflows:
  my-workflow:
    jobs:
      - build