version: 2.1

orbs:
  android: circleci/android@2.2.0
jobs:
  androidSetup:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - checkout
      - android/create-avd:
          avd-name: myavd
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
          avd-name: myavd
          no-window: true
          restore-gradle-cache-prefix: v1a
      - android/run-tests
      - android/save-gradle-cache:
          cache-prefix: v1a
workflows:
  androidTest:
    jobs:
       - androidSetup:
          post-run-tests-steps:
            - store_test_results:
                path: app/build/outputs/androidTest-results/connected
          pre-steps:
            - android/change-java-version:
                java-version: 8