# CircleCI configuration file
version: 2.1

orbs:
  win: circleci/windows@5.0 # The Windows orb gives you everything you need to start using the Windows executor.

jobs:
  build: # name of your job
    executor: win/default # executor type

    steps:
      - checkout
      - run: whoami

workflows:
  my-workflow:
    jobs:
      - build