# CircleCI configuration file
version: 2.1

jobs:
  testJob:
    docker:
    - image: ncino/ci-sfdx
    steps:
      - run: echo "Does this image work?"


workflows:
  workflowtest:
    jobs:
     - testJob
