version: 2.1

orbs:
  win: circleci/windows@5.0.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Install imdisk"
          shell: powershell.exe
          command: |
            choco install imdisk
      - run:
          name: "Imdisk"
          command: |
            imdisk -a -s 512M -m X: -p "/fs:ntfs /q /y"