version: 2.1

orbs:
  android: circleci/android@2.2.0
jobs:
  androidSetup:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    android/change-java-version:
      java-version: 8
    steps:
      - run: java -version
workflows:
  androidTest:
    jobs:
       - androidSetup