# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
     - image: windmillcode/angular-flask-capybara-log4j2:0.0.10
    steps:
        - run: echo "Hello, it me"

workflows:
  hello:
    jobs:
      - build