# CircleCI configuration file
version: 2.1

jobs:
  testJob:
    docker:
    - image: cimg/base:2023.03
    steps:
      - run:
          name: Env Var Print Test
          command: |
              echo "CIRCLE_WORKFLOW_JOB_ID: $CIRCLE_WORKFLOW_JOB_ID"
              echo "CIRCLE_BUILD_NUM: $CIRCLE_BUILD_NUM"
              echo "pipeline.number: $pipeline.number"


workflows:
  workflowtest:
    jobs:
     - testJob

### Update for today
