version: 2.1

workflows:
  workflow-uno:
    jobs:
      - yjit-in-here

jobs:
  yjit-in-here:
    docker:
      - image: cimg/ruby:3.2.1

    steps:
      - checkout
      - run:
          name: Install yjit
          command: |
            RUBY_CONFIGURE_OPTS="--enable-yjit" rbenv install 3.2.0 -force
      - run:
          name: Yjit Installed?
          command: |
            ruby -v --yjit