version: 2.1

orbs:
  android: circleci/android@2.2.0
jobs:
  androidSetup:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - checkout
      - android/create-avd:
          avd-name: myavd
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
          avd-name: myavd
          no-window: true
          restore-gradle-cache-prefix: v1a
      - android/run-tests
      - android/save-gradle-cache:
          cache-prefix: v1a
workflows:
  androidTest:
    jobs:
       - androidSetup:
          executor:
            name: android/android-machine
            resource-class: xlarge
            tag: 2022.09.1
          max-tries: 1
          no-output-timeout: 30m
          additional-emulator-args: "-partition-size 1024"
          matrix:
            parameters:
              system-image:
                - system-images;android-31;default;x86_64
                - system-images;android-30;default;x86_64
                - system-images;android-29;default;x86
                - system-images;android-28;default;x86
                - system-images;android-27;default;x86
          name: ui-tests-<<matrix.system-image>>
          post-run-tests-steps:
            - store_test_results:
                path: app/build/outputs/androidTest-results/connected
          pre-steps:
            - android/change-java-version:
                java-version: 8