version: 2.1

workflows:
  test-login:
    jobs:
      - creds
jobs:
  creds:
    executor: win/server-2022
    steps:
      - run: 
          command: |
            $username = 'Your.Username'
            $password = 'Password in plain text'
            $securePassword = ConvertTo-SecureString $password -AsPlainText -Force 
            $credential = New-Object System.Management.Automation.PSCredential ($username, $securePassword)
            
            Invoke-Command -ComputerName localhost -Credential $credential 
            
          shell: powershell.exe