version: 2.1

jobs:
  build:
    docker:
     - image: cimg/base:2022.05
       environment:
          Rain: Acid
    steps:
      - run: 
          name: Echo Env Var
          command: echo $Rain
      - run:
          name: Is this Project or Job Env Var?
          command: echo $Rain


workflows:
  hello:
    jobs:
      - build