# CircleCI configuration file
version: 2.1

jobs:
  testJob:
    docker:
    - image: salesforce/salesforcedx:7.194.0-full
    steps:
      - run: echo "Hello, from Salesforce!"


workflows:
  workflowtest:
    jobs:
     - testJob

### Comment to update build