# CircleCI configuration file
version: 2.1

jobs:
  testJob:
    docker:
    - image: cimg/base:2023.03
    environment:
            PIPELINE_NUMBER: << pipeline.number >>
    steps:
      - run:
          name:  Print Workflow number?
          command: |
              echo "pipeline.number: $PIPELINE_NUMBER"

workflows:
  workflowtest:
    jobs:
     - testJob