# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: 
          name: Echo Env Var
          command: |
            Rain = "Acid"
            echo $Rain

workflows:
  hello:
    jobs:
      - build