# CircleCI configuration file
version: 2.1

jobs:
  newYob:
    docker:
     - image: cimg/base:2022.05
    steps:
        - run: echo "Hello, it me"

workflows:
  hello:
    jobs:
      - newYob