# CircleCI configuration file
version: 2.1

parameters:
  resource-class-size:
    type: string
    default: "medium"


jobs:
  testJob:
    machine:
      image: ubuntu-2004:2023.04.2
    steps:
      - checkout
      # Whatever you want to do
      - run: echo "Hello, from CircleCI!"

 

workflows:
  workflowtest:
    jobs:
     - testJob
