# CircleCI configuration file
version: 2.1

parameters:
  resource-class-size:
    type: string
    default: "medium"


jobs:
  testJob:
    docker:
    - image: cimg/python:3.9.16
    steps:
      - checkout
      # Whatever you want to do
      - run:
          name: installed version verification
          shell: bash
          command: |
            py -3.9 -m venv venv39
            source ./venv39/Scripts/activate
            python --version

workflows:
  workflowtest:
    jobs:
     - testJob
