version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Check docker"
          shell: bash.exe
          command: |
            docker info
            docker run -it mcr.microsoft.com/windows/nanoserver:ltsc2022 cmd.exe