version: 2.1 # Use version 2.1 to enable Orb usage.

orbs:
  win: circleci/windows@5.0 # The Windows orb gives you everything you need to start using the Windows executor.

jobs:
  build: # name of your job
    executor: win/server-2022 # executor type

    steps:
      # Commands are run in a Windows virtual machine environment
      - checkout
      - run: 
          command: |
            $EdgeExe = Get-ItemPropertyValue 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\msedge.exe' "(default)"
            $version = (Get-Item $EdgeExe).VersionInfo.ProductVersion
            echo $version
          shell: powershell.exe


#how about this time