# CircleCI configuration file
version: 2.1

jobs:
  testJob:
    docker:
      - image: cimg/python:3.9-node
    steps:
      - checkout
      - run:
          name: poetry self update
          command: |
            poetry self update




workflows:
  workflowtest:
    jobs:
     - testJob

### Update for today

